##############
# Grace Cafe #
##############

title: Grace CafÃ©
email: danny.ta1602@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Experience True Simplicity.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://gracegrill.ca" # the base hostname & protocol for your site, e.g. http://example.com
instagram_username: gracecafe
facebook_username: gracecafe

# Build settings
markdown: kramdown

plugins: [bootstrap, autoprefixer-rails, jekyll-assets]

sass:
  sass_dir: _sass